name: build
on: [pull_request, push]

jobs:
    build-with-bazel:
        runs-on: ubuntu-24.04
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
            - uses: bazel-contrib/setup-bazel@0.14.0
              with:
                  bazelisk-cache: true
                  disk-cache: ${{ github.workflow }}
                  repository-cache: true
            - name: build
              run: bazel build --verbose_failures //... > build.log 2>&1
            - name: Prepare artifacts for upload
              run: |
                mkdir -p release_artifacts
                BIN_PATH=$(bazel info bazel-bin)
                for dir in "$BIN_PATH"/*/ ; do
                  dir_name=$(basename "$dir")
                  zip_file="$dir/${dir_name}.zip"
                  if [ -f "$zip_file" ]; then
                    echo "Found artifact: $zip_file"
                    cp "$zip_file" release_artifacts/
                  fi
                done
            - name: capture build artifacts
              if: success()
              uses: actions/upload-artifact@v4
              with:
                  name: artifacts
                  path: release_artifacts/
            - name: Upload build log on failure
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: build-log
                  path: build.log
