name: build
on: [pull_request, push]

jobs:
    build-with-bazel:
        runs-on: ubuntu-24.04
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
            - uses: bazel-contrib/setup-bazel@0.14.0
              with:
                  bazelisk-cache: true
                  disk-cache: ${{ github.workflow }}
                  repository-cache: true
            - name: build
              run: bazel build --verbose_failures //... > build.log 2>&1
            - name: Get bazel-bin path
              id: bazel_path
              run: echo "bin_path=$(bazel info bazel-bin)" >> $GITHUB_OUTPUT
            - name: capture build artifacts
              if: success()
              uses: actions/upload-artifact@v4
              with:
                  name: artifacts
                  path: ${{ steps.bazel_path.outputs.bin_path }}/**/*.zip
            - name: Upload build log on failure
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: build-log
                  path: build.log
