name: Handle Build Failure

on:
  workflow_run:
    workflows: ["build"]
    types:
      - failure

permissions:
  issues: write
  contents: write

jobs:
  handle-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build log
        uses: actions/download-artifact@v4
        with:
          name: build-log
          path: .
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Get commit information
        id: commit_info
        run: |
          echo "short_sha=$(echo ${{ github.event.workflow_run.head_sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
          commit_message=$(git log --format=%B -n 1 ${{ github.event.workflow_run.head_sha }})
          echo "commit_message<<EOF" >> $GITHUB_OUTPUT
          echo "$commit_message" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Check for existing issue
        id: check_issue
        run: |
          issue_count=$(gh issue list --repo ${{ github.repository }} --label "bug" --search "in:title ${{ steps.commit_info.outputs.short_sha }}" | wc -l)
          if [ $issue_count -gt 0 ]; then
            echo "issue_exists=true" >> $GITHUB_OUTPUT
          else
            echo "issue_exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create issue with log
        if: steps.check_issue.outputs.issue_exists == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: ${{ steps.commit_info.outputs.commit_message }}
          SHORT_SHA: ${{ steps.commit_info.outputs.short_sha }}
          HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
          RUN_URL: ${{ github.event.workflow_run.html_url }}
          REPO: ${{ github.repository }}
          SERVER_URL: ${{ github.server_url }}
        run: |
          LOG_BODY=$(tail -c 40000 build.log)

          cat <<EOF > issue-body.md
          构建在 commit [$SHORT_SHA]($SERVER_URL/$REPO/commit/$HEAD_SHA) 失败。

          **Commit Message:**
          $COMMIT_MESSAGE

          [查看失败的构建]($RUN_URL)

          <details>
          <summary>构建日志 (末尾 40kb)</summary>

          ```
          $LOG_BODY
          ```
          </details>
          EOF

          gh issue create --repo $REPO \
            --title "$SHORT_SHA 构建失败" \
            --body-file issue-body.md \
            --label "bug"